/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChanDoanRouteImport } from './routes/chan-doan'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as DanhGiaLaiRouteImport } from './routes/danh-gia-lai'
import { Route as GoiDichVuRouteImport } from './routes/goi-dich-vu'
import { Route as KhoangCachRouteImport } from './routes/khoang-cach'
import { Route as KhuyenNghiRouteImport } from './routes/khuyen-nghi'
import { Route as MaTranRouteImport } from './routes/ma-tran'
import { Route as MinhBachRouteImport } from './routes/minh-bach'
import { Route as NhapLieuRouteImport } from './routes/nhap-lieu'
import { Route as TongQuanRouteImport } from './routes/tong-quan'
import { Route as TruVanHanhRouteImport } from './routes/tru-van-hanh'
import { Route as DoanhNghiepCodeRouteImport } from './routes/doanh-nghiep/$code'
import { Route as KhaoSatCodeRouteImport } from './routes/khao-sat/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChanDoanRoute = ChanDoanRouteImport.update({
  id: '/chan-doan',
  path: '/chan-doan',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhGiaLaiRoute = DanhGiaLaiRouteImport.update({
  id: '/danh-gia-lai',
  path: '/danh-gia-lai',
  getParentRoute: () => rootRouteImport,
} as any)
const GoiDichVuRoute = GoiDichVuRouteImport.update({
  id: '/goi-dich-vu',
  path: '/goi-dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoangCachRoute = KhoangCachRouteImport.update({
  id: '/khoang-cach',
  path: '/khoang-cach',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuyenNghiRoute = KhuyenNghiRouteImport.update({
  id: '/khuyen-nghi',
  path: '/khuyen-nghi',
  getParentRoute: () => rootRouteImport,
} as any)
const MaTranRoute = MaTranRouteImport.update({
  id: '/ma-tran',
  path: '/ma-tran',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhBachRoute = MinhBachRouteImport.update({
  id: '/minh-bach',
  path: '/minh-bach',
  getParentRoute: () => rootRouteImport,
} as any)
const NhapLieuRoute = NhapLieuRouteImport.update({
  id: '/nhap-lieu',
  path: '/nhap-lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const TongQuanRoute = TongQuanRouteImport.update({
  id: '/tong-quan',
  path: '/tong-quan',
  getParentRoute: () => rootRouteImport,
} as any)
const TruVanHanhRoute = TruVanHanhRouteImport.update({
  id: '/tru-van-hanh',
  path: '/tru-van-hanh',
  getParentRoute: () => rootRouteImport,
} as any)
const DoanhNghiepCodeRoute = DoanhNghiepCodeRouteImport.update({
  id: '/doanh-nghiep/$code',
  path: '/doanh-nghiep/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const KhaoSatCodeRoute = KhaoSatCodeRouteImport.update({
  id: '/khao-sat/$code',
  path: '/khao-sat/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chan-doan': typeof ChanDoanRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/danh-gia-lai': typeof DanhGiaLaiRoute
  '/goi-dich-vu': typeof GoiDichVuRoute
  '/khoang-cach': typeof KhoangCachRoute
  '/khuyen-nghi': typeof KhuyenNghiRoute
  '/ma-tran': typeof MaTranRoute
  '/minh-bach': typeof MinhBachRoute
  '/nhap-lieu': typeof NhapLieuRoute
  '/tong-quan': typeof TongQuanRoute
  '/tru-van-hanh': typeof TruVanHanhRoute
  '/doanh-nghiep/$code': typeof DoanhNghiepCodeRoute
  '/khao-sat/$code': typeof KhaoSatCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chan-doan': typeof ChanDoanRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/danh-gia-lai': typeof DanhGiaLaiRoute
  '/goi-dich-vu': typeof GoiDichVuRoute
  '/khoang-cach': typeof KhoangCachRoute
  '/khuyen-nghi': typeof KhuyenNghiRoute
  '/ma-tran': typeof MaTranRoute
  '/minh-bach': typeof MinhBachRoute
  '/nhap-lieu': typeof NhapLieuRoute
  '/tong-quan': typeof TongQuanRoute
  '/tru-van-hanh': typeof TruVanHanhRoute
  '/doanh-nghiep/$code': typeof DoanhNghiepCodeRoute
  '/khao-sat/$code': typeof KhaoSatCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chan-doan': typeof ChanDoanRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/danh-gia-lai': typeof DanhGiaLaiRoute
  '/goi-dich-vu': typeof GoiDichVuRoute
  '/khoang-cach': typeof KhoangCachRoute
  '/khuyen-nghi': typeof KhuyenNghiRoute
  '/ma-tran': typeof MaTranRoute
  '/minh-bach': typeof MinhBachRoute
  '/nhap-lieu': typeof NhapLieuRoute
  '/tong-quan': typeof TongQuanRoute
  '/tru-van-hanh': typeof TruVanHanhRoute
  '/doanh-nghiep/$code': typeof DoanhNghiepCodeRoute
  '/khao-sat/$code': typeof KhaoSatCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chan-doan'
    | '/dang-ky'
    | '/dang-nhap'
    | '/danh-gia-lai'
    | '/goi-dich-vu'
    | '/khoang-cach'
    | '/khuyen-nghi'
    | '/ma-tran'
    | '/minh-bach'
    | '/nhap-lieu'
    | '/tong-quan'
    | '/tru-van-hanh'
    | '/doanh-nghiep/$code'
    | '/khao-sat/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chan-doan'
    | '/dang-ky'
    | '/dang-nhap'
    | '/danh-gia-lai'
    | '/goi-dich-vu'
    | '/khoang-cach'
    | '/khuyen-nghi'
    | '/ma-tran'
    | '/minh-bach'
    | '/nhap-lieu'
    | '/tong-quan'
    | '/tru-van-hanh'
    | '/doanh-nghiep/$code'
    | '/khao-sat/$code'
  id:
    | '__root__'
    | '/'
    | '/chan-doan'
    | '/dang-ky'
    | '/dang-nhap'
    | '/danh-gia-lai'
    | '/goi-dich-vu'
    | '/khoang-cach'
    | '/khuyen-nghi'
    | '/ma-tran'
    | '/minh-bach'
    | '/nhap-lieu'
    | '/tong-quan'
    | '/tru-van-hanh'
    | '/doanh-nghiep/$code'
    | '/khao-sat/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChanDoanRoute: typeof ChanDoanRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  DanhGiaLaiRoute: typeof DanhGiaLaiRoute
  GoiDichVuRoute: typeof GoiDichVuRoute
  KhoangCachRoute: typeof KhoangCachRoute
  KhuyenNghiRoute: typeof KhuyenNghiRoute
  MaTranRoute: typeof MaTranRoute
  MinhBachRoute: typeof MinhBachRoute
  NhapLieuRoute: typeof NhapLieuRoute
  TongQuanRoute: typeof TongQuanRoute
  TruVanHanhRoute: typeof TruVanHanhRoute
  DoanhNghiepCodeRoute: typeof DoanhNghiepCodeRoute
  KhaoSatCodeRoute: typeof KhaoSatCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chan-doan': {
      id: '/chan-doan'
      path: '/chan-doan'
      fullPath: '/chan-doan'
      preLoaderRoute: typeof ChanDoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-gia-lai': {
      id: '/danh-gia-lai'
      path: '/danh-gia-lai'
      fullPath: '/danh-gia-lai'
      preLoaderRoute: typeof DanhGiaLaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goi-dich-vu': {
      id: '/goi-dich-vu'
      path: '/goi-dich-vu'
      fullPath: '/goi-dich-vu'
      preLoaderRoute: typeof GoiDichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoang-cach': {
      id: '/khoang-cach'
      path: '/khoang-cach'
      fullPath: '/khoang-cach'
      preLoaderRoute: typeof KhoangCachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khuyen-nghi': {
      id: '/khuyen-nghi'
      path: '/khuyen-nghi'
      fullPath: '/khuyen-nghi'
      preLoaderRoute: typeof KhuyenNghiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ma-tran': {
      id: '/ma-tran'
      path: '/ma-tran'
      fullPath: '/ma-tran'
      preLoaderRoute: typeof MaTranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minh-bach': {
      id: '/minh-bach'
      path: '/minh-bach'
      fullPath: '/minh-bach'
      preLoaderRoute: typeof MinhBachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhap-lieu': {
      id: '/nhap-lieu'
      path: '/nhap-lieu'
      fullPath: '/nhap-lieu'
      preLoaderRoute: typeof NhapLieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tong-quan': {
      id: '/tong-quan'
      path: '/tong-quan'
      fullPath: '/tong-quan'
      preLoaderRoute: typeof TongQuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tru-van-hanh': {
      id: '/tru-van-hanh'
      path: '/tru-van-hanh'
      fullPath: '/tru-van-hanh'
      preLoaderRoute: typeof TruVanHanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doanh-nghiep/$code': {
      id: '/doanh-nghiep/$code'
      path: '/doanh-nghiep/$code'
      fullPath: '/doanh-nghiep/$code'
      preLoaderRoute: typeof DoanhNghiepCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khao-sat/$code': {
      id: '/khao-sat/$code'
      path: '/khao-sat/$code'
      fullPath: '/khao-sat/$code'
      preLoaderRoute: typeof KhaoSatCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChanDoanRoute: ChanDoanRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  DanhGiaLaiRoute: DanhGiaLaiRoute,
  GoiDichVuRoute: GoiDichVuRoute,
  KhoangCachRoute: KhoangCachRoute,
  KhuyenNghiRoute: KhuyenNghiRoute,
  MaTranRoute: MaTranRoute,
  MinhBachRoute: MinhBachRoute,
  NhapLieuRoute: NhapLieuRoute,
  TongQuanRoute: TongQuanRoute,
  TruVanHanhRoute: TruVanHanhRoute,
  DoanhNghiepCodeRoute: DoanhNghiepCodeRoute,
  KhaoSatCodeRoute: KhaoSatCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
